### ISSUE TITLE
Custom Makevars causes installation to fail

### ISSUE THREAD

**Issue by souzapd** [2005m/kit#35] opened 2023-02-03 23:28 UTC
Building from source on macOS 12.6.3 (M1) with a custom Makevars file causes the installation to fail.

I have a `~/.R/Makevars` file to install `{data.table}` with OpenMP support as follows:

```make
# if you downloaded llvm manually above, replace with your chosen NEW_PATH/clang
LLVM_LOC = /opt/homebrew/opt/llvm
CC=$(LLVM_LOC)/bin/clang -fopenmp
CXX=$(LLVM_LOC)/bin/clang++ -fopenmp

# -O3 should be faster than -O2 (default) level optimisation ..
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/opt/homebrew/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib
CPPFLAGS=-I/opt/homebrew/opt/gettext/include -I$(LLVM_LOC)/include
```

But when trying to install `{kit}`, I get the following status:

```R
install.packages('kit', dependencies=TRUE)
Installing package into ‘/opt/homebrew/lib/R/4.2/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mirror.garr.it/CRAN/src/contrib/kit_0.0.12.tar.gz'
Content type 'application/octet-stream' length 92606 bytes (90 KB)
==================================================
downloaded 90 KB

* installing *source* package ‘kit’ ...
** package ‘kit’ successfully unpacked and MD5 sums checked
** using staged installation
*** On Linux and OpenMP supported!

## -- Verbose output -- 

/opt/homebrew/opt/llvm/bin/clang -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.2.2_1/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib -o kit.so dup.o dupLen.o fpos.o iif.o init.o nswitch.o psort.o psum.o share.o topn.o utils.o vswitch.o -lrt -L/opt/homebrew/Cellar/r/4.2.2_1/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
ld: library not found for -lrt
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [kit.so] Error 1
ERROR: compilation failed for package ‘kit’
```

And then I get a `installation of package ‘kit’ had non-zero exit status` message.

Commenting the lines in the Makevars file solves the issue, but I feel like removing the `-lrt` flag should solve the issue.

**Comment by 2005m** [comment] 2023-02-04 04:48
I can't reproduce your issue because I don't have the hardware.

1/ Try to download the source package from CRAN

2/ Change the "configure" file in the tar.gz archive , see 3/

3/ Try to change the following line (25) in file "configure":
```
sed -e "s|@openmp_cflags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@openmp_libslags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@realtime_libslags@|-lrt|g;" src/Makevars.in > src/Makevars
```

To

```
sed -e "s|@openmp_cflags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@openmp_libslags@|\$(SHLIB_OPENMP_CFLAGS)|g; s|@realtime_libslags@|g;" src/Makevars.in > src/Makevars
```
4/ Save the "configure" file and the archive.

5/ Install the modified tar.gz archive.

**Comment by souzapd** [comment] 2023-02-04 13:11
Good morning, @2005m.

I adjusted line 25 as instructed, created a new tarball and installation succeeded. Loading the library, I get the following message:

```R
Attaching kit 0.0.12 (OPENMP enabled using 1 thread)
```

I got two kinds of warnings as well: one is related to function declaration without a prototype, and the other concerns an undefined dynamic lookup. Although the library has been successfully installed and loaded, for the sake of completion, I am listing them: 

For the former has the following format:

```R 
1 warning generated.
/opt/homebrew/opt/llvm/bin/clang -fopenmp -I"/opt/homebrew/Cellar/r/4.2.2_1/lib/R/include" -DNDEBUG   -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/llvm/include   -fPIC  -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -c (FILE).c -o (FILE).o
In file included from (FILE).c:(line_number):
In file included from ./kit.h:16:
/opt/homebrew/Cellar/r/4.2.2_1/lib/R/include/R_ext/Rdynload.h:38:26: warning: a function
      declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
typedef void * (*DL_FUNC)();
                         ^
                          void
``` 

The affected files and the signalled lines are as follows: 
* `dup.c:19`
* `dupLen.c:19`
* `fpos.c:19`
* `iif.c:19`
* `init.c:1`
* `nswitch.c:19`
* `psort.c:19`
* `psum.c:19`
* `share.c:19`
* `topn.c:19`
* `utils.c:19`
* `vswitch.c:19`


For the latter, here is the output in full.

```R
/opt/homebrew/opt/llvm/bin/clang -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.2.2_1/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib -o kit.so dup.o dupLen.o fpos.o iif.o init.o nswitch.o psort.o psum.o share.o topn.o utils.o vswitch.o -L/opt/homebrew/Cellar/r/4.2.2_1/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```

If you need any more help, let me know.

**Comment by 2005m** [comment] 2023-02-04 15:42
The first warning is coming from the core R library  and seems to have been fixed in the source code.

https://github.com/wch/r-source/commit/f9a19f8e6aa664c84bb856ffd6dfd4c4bd913508

The second warning is not clear to me. The below link seems to be related

https://developer.apple.com/forums/thread/719961

Are you using a recent compiler?
Also as mentionned I don't have a hardware to try to reproduce your issue so it is quite difficult for me to help.
On CRAN, the package seems to be passing all the checks without issues: https://cran.r-project.org/web/checks/check_results_kit.html
Last thing that I can suggest you is to run the file called tests/test_kit.R that is in this package to see if it passes all the checks om your system.
Hope it helps!

**Comment by souzapd** [comment] 2023-02-04 19:06
I have run the test, everything is fine. I'll keep an eye on the Apple ticket you linked.

Concerning the compiler, I am using R installed by Homebrew, which has a dependency on gcc (also available through `brew`). 

```make
% /opt/homebrew/Cellar/gcc/12.2.0/bin/gcc-12 --version 
gcc-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.

% /opt/homebrew/Cellar/gcc/12.2.0/bin/g++-12 --version
g++-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
```

Guess everything is right now, time to acquaint myself with the package and fastverse.

Thanks for your support and patience, @2005m.

**Comment by 2005m** [comment] 2023-02-05 08:22
I have updated the `configure` file in the master branch so you don't have to change it on your side.
Can you let me know whether it is still ok for you when you install the package?
Thank you

**Comment by souzapd** [comment] 2023-02-05 11:34
Hi, I generated the tarball from the master branch and installation went through without a hitch.

Thank you!

**Comment by 2005m** [comment] 2023-02-05 13:00
Did you still have the warnings?

**Comment by souzapd** [comment] 2023-02-05 13:22
Yes, I still got the same warnings I related when I opened this issue, but the package installed correctly, the test suite runs without issues, and the package loads and functions as expected. 

Given that you mentioned that the CRAN tests haven't raised or signalled anything either, I think the issue is solved.

**Comment by 2005m** [comment] 2023-02-05 22:46
Thank you

**Closed as completed by 2005m** 2023-02-05 22:46 UTC
